---
title: "Exercise 6"
author: "Carilli"
date: '`r format(lubridate::today(), "%B %d, %Y")`'
output: 
  html_document:
    theme: cerulean
    highlight: tango
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, warning = FALSE, message = FALSE,
                      options(digits = 3, scipen = 999))
library(tidyverse)
library(plm)
```

```{r 6data}
cell <- 
  here::here("data", "Cellphone_Panel_homework.csv") %>% 
  read_csv() %>% 
  janitor::clean_names() %>% 
  mutate(state = factor(state),
         year = factor(year))

```

### (a)

```{r 6a}
cell %>% 
  lm(deaths_per_billion_miles ~ cell_ban + text_ban, .) %>% 
  jtools::summ()
```

### (b)

### (c)

```{r 6c}
cell %>% 
plm(deaths_per_billion_miles ~ cell_ban + text_ban,
    data = ., index = "state", model = "within") %>% 
  broom::tidy()
```

### (d)

### (e)

```{r 6e}
cell %>% 
  plm(deaths_per_billion_miles ~ cell_ban + text_ban, .,
      index = c("state", "year"), model = "within", effect = "twoways") %>% 
  broom::tidy() 

cell %>% 
  plm(deaths_per_billion_miles ~ cell_ban + text_ban + year, .,
      index = c("state"), model = "within") %>% 
  broom::tidy()
```

```{r 6e-2}
cell %>% 
  group_by(year) %>% 
  summarize(Pct_Cell = mean(cell_ban),
            Pct_Text = mean(text_ban),
            Death = mean(deaths_per_billion_miles)) 
```

### (f)

```{r 6f}
cell %>% 
  plm(deaths_per_billion_miles ~ cell_ban + text_ban + urban_percent + 
        cell_per10thous_pop + year,
    data = ., index = c("state", "year"), model = "within") %>% 
  broom::tidy() 
```

### (g)

```{r 6g}
cell %>%
  lm(
    deaths_per_billion_miles ~ cell_ban + text_ban +
      year + state + urban_percent + cell_per10thous_pop,
    .
  ) %>%
  broom::tidy() 

cell %>%
  plm(
    deaths_per_billion_miles ~ cell_ban + text_ban +
      cell_per10thous_pop + urban_percent,
    data = .,
    index = c("year", "state"),
    model = "within",
    effect = "twoways"
  ) %>%
  broom::tidy()
```

### (h)


```{r 6h}

cell %>%
  plm(
    deaths_per_billion_miles ~ cell_ban + text_ban +
      cell_per10thous_pop + urban_percent,
    data = .,
    index = c("year", "state"),
    model = "within",
    effect = "twoways"
  ) %>%
  broom::tidy()

cell %>%
  plm(
    deaths_per_billion_miles ~ cell_ban + text_ban +
      cell_per10thous_pop + urban_percent,
    data = .,
    index = c("year", "state"),
    model = "within",
    effect = "twoways"
  ) %>%
  broom::glance()

cell %>%
  plm(
    deaths_per_billion_miles ~ cell_ban + text_ban +
      cell_per10thous_pop + urban_percent,
    data = .,
    index = c("year", "state"),
    model = "within",
    effect = "twoways"
  ) %>%
  broom::augment()


cell %>%
  plm(
    deaths_per_billion_miles ~ cell_ban + text_ban +
      cell_per10thous_pop + urban_percent,
    data = .,
    index = c("state", "year"),
    model = "within",
    effect = "twoways"
  ) %>%
  fixef() %>%
  as_tibble() %>%
  mutate(state = cell$state[1:51],
         fixed_effect = scale(value, scale = FALSE)) %>%
  select(state, fixed_effect) %>%
  top_n(5)

cell %>%
  plm(
    deaths_per_billion_miles ~ cell_ban + text_ban +
      cell_per10thous_pop + urban_percent,
    data = .,
    index = c("state", "year"),
    model = "within",
    effect = "twoways"
  ) %>%
  fixef() %>%
  as_tibble() %>%
  mutate(state = cell$state[1:51],
         fixed_effect = scale(value, scale = FALSE)) %>%
  select(state, fixed_effect) %>%
  top_n(-5)
```

