---
title: "Exercise 4"
author: "Carilli"
date: '`r format(lubridate::today(), "%B %d, %Y")`'
output: 
  html_document:
    theme: cerulean
    highlight: tango
    code_folding: hide
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, warning = FALSE, message = FALSE,
                      options(digits = 3, scipen = 999))
library(tidyverse)
library(plm)
```

```{r 4data}
hope <- 
  here::here("data", "HOPE_HW.csv") %>% 
  read_csv() %>% 
  janitor::clean_names() %>% 
  mutate(year = factor(year))
  #        state = factor(state_code),
  #        georgia = factor(georgia),
  #        after_georgia = factor(after_georgia),
  #        after = factor(after),
  #        in_college = factor(in_college),
  #        low_income = factor(low_income),
  #        age_18 = factor(age18),
  #        black = factor(black))
```

### (a)

```{r 4a}
hope %>% 
  lm(in_college ~ georgia * after , .) %>% 
  jtools::summ(digits = 4)
```

equatiomatic

```{r equatiomatic, results='asis'}
hope %>% 
  lm(in_college ~ georgia * after , .) %>% 
  equatiomatic::extract_eq(intercept = "beta",
                           use_coefs = TRUE,
                           coef_digits = 4,
                           ital_vars = TRUE)

```


### (b)

```{r 4b1}
hope %>% 
  group_by(georgia, after) %>% 
  summarize(percent = mean(in_college)) 
```

```{r 4b2}
hope %>% 
  lm(in_college ~ georgia * after, .) %>% 
  broom::tidy() %>% 
  select(term, estimate) %>% 
  summarize(before_non_georgia = estimate[1],
            after_non_georgia = estimate[1] + estimate[3],
            before_georgia = estimate[1] + estimate[2],
            after_georgia = sum(estimate[1:4]))
```

### (c)

```{r 4c}
hope %>% 
  ggplot(aes(x = after, y = in_college, color = factor(georgia))) +
  geom_smooth(method = "lm", se = FALSE) +
  xlab("Time") + 
  ylab("Percent in College") +
  expand_limits(x = 0, y = 0) +
  labs(color = "Georgia")
```

### (d)

```{r 4d}
hope %>% 
plm(in_college ~ after_georgia + year, ., 
    index = "state_code", model = "within") %>% 
  broom::tidy() %>% 
  slice(1)
```

### (e)

```{r 4e}
hope %>% 
plm(in_college ~ after_georgia + age18 + black + year, .,
    index = "state_code", model = "within") %>% 
  broom::tidy() %>% 
  slice(1:3)
```

### (f)

```{r 4f}
hope %>% 
  lm(in_college ~ low_income + age18 + black + after * georgia, .) %>% 
  jtools::summ(digits = 4)

hope %>% 
plm(in_college ~ low_income + after_georgia + age18 + black + year, .,
    index = "state_code", model = "within") %>% 
  broom::tidy() %>% 
  slice(1:4)
```


