---
title: "Exercise 1"
author: "Carilli"
date: '`r format(lubridate::today(), "%B %d, %Y")`'
output: 
  html_document:
    theme: cerulean
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, warning = FALSE, message = FALSE,
                      options(digits = 3, scipen = 999))
library(tidyverse)
library(plm)
```

```{r 1data}
pres_app <- 
  here::here("data", "presapproval_HW_edited.csv") %>% 
  read_csv() %>% 
  janitor::clean_names()
```

### (a)

```{r 1a}
pres_app %>% 
  lm(pres_approv ~ unem_pct, .) %>% 
  jtools::summ()
```

### (b)

```{r 1b} 
pres_app %>% 
  lm(pres_approv ~ unem_pct + south, .) %>% 
  jtools::summ()
```

### (c)

```{r}
pres_app %>% 
  mutate(unem_pct = scale(unem_pct, scale = F),
         pres_approv = scale(pres_approv, scale = F)) %>% 
  lm(pres_approv ~ unem_pct + factor(state), .) %>% 
  jtools::summ()

pres_app %>% 
plm(pres_approv ~ unem_pct, ., index = "state", model = "within") %>% 
  summary()

pres_app %>% 
  lm(pres_approv ~ unem_pct + factor(state), .) %>% 
  jtools::summ(center = TRUE, transform.response = TRUE)
```

### (d)

```{r}
pres_app %>% 
  lm(pres_approv ~ unem_pct + factor(state), .) %>% 
  jtools::summ()
```

### (e)

```{r}
pres_app %>% 
plm(pres_approv ~ unem_pct + factor(year), ., index = "state", model = "within") %>% 
  summary()
```

